services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/netflixAPI
    depends_on:
      - php
      - mysql
    hostname: netflix.local
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/netflixAPI
      - ./files:/var/www/netflixAPI/files
    expose:
      - "9000"
    environment:
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: "serverName=localhost"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    env_file:
      - ./docker/mysql/.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: